os: linux

services:
  - docker

# install:
#   - docker login -u $USERNAME -p $PASSWORD

# script:
#   - docker image build -t $USERNAME/flask-app .
script:
  - echo "Hello"

deploy:
  provider: heroku
  app: flask-app-shudarshan
  api-key: $HEROKU_API_KEY
